#! /bin/sh

# ┌─┐┬  ┌─┐┬ ┬┌─┐┌┬┐┌─┐┬ ┬
# ├┤ │  │ ││││├┤  │ │  ├─┤
# └  ┴─┘└─┘└┴┘└─┘ ┴ └─┘┴ ┴

#####################
# Information
#####################

# Packages

if command -v pacman >/dev/null
then
  pkg="$(pacman -Qq | wc -l)"
elif  command -v dpkg >/dev/null
then
  pkg="$(dpkg -l | wc -l)"
elif  command -v xbps-query >/dev/null
then
    pkg="$(xbps-query -l | wc -l)"
else
  pkg="$(rpm -qa | wc -l)"
fi

# Get user
user="${USER-$(id -u -n)}"

# Get host
host="$(uname -n)"

# Get OS
. /etc/os-release
os="$NAME"

# Get uptime
uptime="$(echo $(awk '{print $1}' /proc/uptime) / 3600 | bc)"

# Shell
shell="${SHELL##*/}"

#####################
# Display protocol
#####################

[ "$DISPLAY" ] && displayprot="x11"
[ "$WAYLAND_DISPLAY" ] && displayprot="wayland"
[ ! "$displayprot" ] && displayprot="tty"

#####################
# GTK 3
#####################

while read -r line; do
  case $line in
  gtk-theme*) theme=${line##*=} ;;
  gtk-icon-theme*) icons=${line##*=} ;;
  esac
done <"${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"

#####################
# GTK theme
#####################

wm="$XDG_CURRENT_DESKTOP"
[ "$wm" ] || wm="$DESKTOP_SESSION"

#####################
# Window Manager
#####################

[ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
  id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
  id=${id##* }
  wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
    grep '^_NET_WM_NAME' | cut -d\" -f 2)
}

#####################
# For non-EWH WMs
#####################

[ ! "$wm" ] || [ "$wm" = "LG3D" ] &&
  wm=$(
    ps -e | grep -m 1 -o \
      -e "sway" \
      -e "kiwmi" \
      -e "wayfire" \
      -e "sowm" \
      -e "catwm" \
      -e "fvwm" \
      -e "dwm" \
      -e "2bwm" \
      -e "monsterwm" \
      -e "tinywm" \
      -e "xmonad"
  )

#####################
# GTK theme
#####################

case $wm in
*GNOME*)
  theme=$(dconf read /org/gnome/desktop/interface/gtk-theme | tr -d "'")
  icons=$(dconf read /org/gnome/desktop/interface/icon-theme | tr -d "'")
  ;;
*)
  while read -r line; do
    case $line in
    gtk-theme*) theme=${line##*=} ;;
    gtk-icon-theme*) icons=${line##*=} ;;
    esac
  done <"${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
  ;;
esac

#####################
# Colors
#####################

c0=' [0m'
c1=' [31m'
c2=' [32m'
c3=' [33m'
c4=' [34m'
c5=' [35m'
c6=' [36m'
c7=' [37m'
c8=' [38m'
c9='^[[37m'

#####################
# Art
#####################

ARTR1="${c5}           ⢠⣿⣶⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀  "
ARTR2="${c5}⠀⠀⠀⠀⠀⠀⠀  ⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣦⣄⣀⡀⣠⣾⡇⠀⠀⠀⠀  "
ARTR3="${c5}        ⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀  "
ARTR4="${c5}      ⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⢿⣿⣿⡇⠀⠀⠀⠀  "
ARTR5="${c5}   ⣶⣿⣦⣜⣿⣿⣿⡟⠻⣿⣿⣿⣿⣿⣿⣿⡿⢿⡏⣴⣺⣦⣙⣿⣷⣄⠀⠀⠀  "
ARTR6="${c5}  ⠀⣯⡇⣻⣿⣿⣿⣿⣷⣾⣿⣬⣥⣭⣽⣿⣿⣧⣼⡇⣯⣇⣹⣿⣿⣿⣿⣧    "
ARTR7="${c5}   ⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠸⣿⣿⣿⣿⣿⣿⣿⣷⠀  "


#####################
# Main Print
#####################

cat <<-EOF

 ${ARTR1}  ${c4}host${c0}    ${c4}•••   ${host}
 ${ARTR2}  ${c4}os${c0}      ${c1}•••   ${os}
 ${ARTR3}  ${c4}user${c0}    ${c5}•••   ${user}
 ${ARTR4}  ${c4}shell${c0}   ${c2}•••   ${shell}
 ${ARTR5}  ${c4}wm${c0}      ${c6}•••   ${wm}
 ${ARTR6}  ${c4}theme${c0}   ${c3}•••   ${theme}
 ${ARTR7}  ${c4}pkg${c0}     ${c7}•••   ${pkg}

EOF
